version: "3"

services:
  traefik:
    image: traefik
    restart: always
    container_name: traefik
    command:
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.dashboard.service=api@internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

<<<<<<< HEAD
networks:
  default:
    external:
      name: hostnet
=======
volumes:
  traefik-certificates:
>>>>>>> d648e472e5e4f5acae3ccb30fcccfcbbcb392eff
