## traefik.yml
## Static configuration
entryPoints:
  web:
    address: ":80" # same as ":8888/tcp"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 42
        graceTimeOut: 42
      respondingTimeouts:
        readTimeout: 42
        writeTimeout: 42
        idleTimeout: 42
    proxyProtocol:
      insecure: true
      trustedIPs:
        - "127.0.0.1"
    forwardedHeaders:
      insecure: true
      trustedIPs:
        - "127.0.0.1"

  websecure:
    address: ":443"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 42
        graceTimeOut: 42
      respondingTimeouts:
        readTimeout: 42
        writeTimeout: 42
        idleTimeout: 42
    proxyProtocol:
      insecure: false
      trustedIPs:
        - "127.0.0.1"
    forwardedHeaders:
      insecure: false
      trustedIPs:
        - "127.0.0.1"

# Docker configuration backend
providers:
  docker: {}

# API and dashboard configuration
api:
  insecure: true


